framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            redis_async:
                dsn: '%env(REDIS_MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            doctrine_async:
                dsn: '%env(DOCTRINE_MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: redis_async
            Symfony\Component\Notifier\Message\ChatMessage: redis_async
            Symfony\Component\Notifier\Message\SmsMessage: redis_async
            App\Service\Message\SendEmailMessage: redis_async
