env:
  browser: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent: ['error', 4]
  no-alert: 'off'
  no-param-reassign: 'off'
  no-use-before-define: 'off'
globals:
  $: readonly
  jQuery: readonly
  Glide: readonly
