controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

_locale_prefix:
    resource: ../src/Controller/**/*
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: en|pl|de|fr|es|it|ru|nl
    defaults: { _locale: pl }

root_redirect:
    path: /
    controller: App\Controller\LanguageController::changeLanguage
