controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

_locale_prefix:
    resource: ../src/Controller/**/*
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: pl|en|de|fr|es|it|sv|no|fi|uk|nl|lt|da|et|cs|sk|lv|ro|hr|hu|bg|sr|sl|ru|el
    defaults: { _locale: en }

default_redirect:
    path: /
    controller: App\Controller\LanguageController::redirectToDefaultLanguage
