name: Continuous Integration

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Check PHP version
        run: php -v

      - name: Install Composer dependencies
        run: composer install

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '>=20.10.0'

      - name: Install npm dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint assets/js/

      - name: Run Stylelint
        run: npx stylelint "assets/styles/**/*.scss"

      - name: Run PHPCsFixer
        run: vendor/bin/php-cs-fixer check --allow-risky-yes

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
